# Generated by Django 5.0.6 on 2024-05-21 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='is_featured_destination',
            new_name='is_popular_place',
        ),
        migrations.RemoveField(
            model_name='place',
            name='is_hotel',
        ),
        migrations.RemoveField(
            model_name='place',
            name='is_popular_hotel',
        ),
        migrations.AddField(
            model_name='city',
            name='city_slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='is_featured_destination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hotel_address', models.CharField(blank=True, max_length=100, null=True)),
                ('hotel_desc', models.TextField()),
                ('hotel_image', models.ImageField(upload_to='hotel_images')),
                ('hotel_price', models.PositiveIntegerField(default=0)),
                ('hotel_rooms', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('is_popular_hotel', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='myapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_email', models.EmailField(max_length=254)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('num_adults', models.PositiveIntegerField(default=1)),
                ('num_children', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='myapp.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='myapp.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelFeatureImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_images')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='myapp.hotel')),
            ],
            options={
                'verbose_name_plural': 'Hotel Feature Images',
            },
        ),
    ]
