# Generated by Django 5.0.6 on 2024-05-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_is_featured_destination_place_is_popular_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='is_popular_place',
        ),
        migrations.AddField(
            model_name='city',
            name='is_popular_place',
            field=models.BooleanField(default=False),
        ),
    ]
