# Generated by Django 5.0.6 on 2024-05-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_place_is_popular_place_city_is_popular_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='is_featured_destination',
        ),
    ]
