# Generated by Django 5.0.6 on 2024-05-24 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceFeatureImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='place_images')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_images', to='myapp.place')),
            ],
        ),
    ]
