# Generated by Django 5.0.6 on 2024-05-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_booking_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_of_rooms',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
